import { useState } from 'react';
import { hasSupabaseSession, signIn, signOut, signUp, supabaseConfigured, syncNow } from './supabase';

export function SyncPanel({ onChange }: { onChange: () => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const [logged, setLogged] = useState(hasSupabaseSession());
  async function synchronize() { setBusy(true); try { const result = await syncNow(); setStatus(result.message); onChange(); } catch (e) { setStatus(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  if (!supabaseConfigured) return <details className="backup-panel"><summary>Sincronización</summary><p>Falta configurar Supabase en el despliegue.</p></details>;
  async function submit(register: boolean) { setBusy(true); setStatus(''); try { const result = register ? await signUp(email, password) : await signIn(email, password); if (!result.access_token) setStatus('Revisá tu correo para confirmar la cuenta.'); else { setLogged(true); await syncNow(); onChange(); setStatus('Cuenta conectada y datos sincronizados.'); } } catch (e) { setStatus(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  if (logged) return <details className="backup-panel"><summary>Sincronización conectada</summary><p>Usá la misma cuenta en tus dispositivos.</p><button disabled={busy} onClick={() => void synchronize()}>{busy ? 'Sincronizando…' : 'Sincronizar ahora'}</button><button disabled={busy} onClick={() => { signOut(); setLogged(false); setPassword(''); setStatus('Sesión cerrada. Los libros siguen en este dispositivo.'); }}>Cerrar sesión</button><p role="status">{status}</p></details>;
  return <details className="backup-panel"><summary>Sincronizar entre dispositivos</summary><p>Usá la misma cuenta en PC y iPhone. La contraseña se envía directamente a Supabase y no se guarda en el código.</p><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email"/></label><label>Contraseña<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password"/></label><div className="quote-actions"><button disabled={busy || !email || password.length < 6} onClick={() => void submit(false)}>Iniciar sesión</button><button disabled={busy || !email || password.length < 6} onClick={() => void submit(true)}>Crear cuenta</button></div><p role="status">{status}</p></details>;
}
