import { expect, test } from '@playwright/test';
import { chapterPDF } from '../fixture';

test('guardar mientras Dora lee, editar y conservar citas al reabrir', async ({page, context}) => {
  await context.grantPermissions(['clipboard-read','clipboard-write']);
  await context.route('**/*', route => ['localhost','127.0.0.1'].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
  await page.goto('/');
  await page.getByLabel('Agregar PDF').setInputFiles({name:'citas.pdf',mimeType:'application/pdf',buffer:chapterPDF('Ensayos de prueba','Pensar nos ayuda a elegir cuando volvemos sobre nuestras dudas y descubrimos que la libertad exige paciencia, memoria y atención.')});
  await expect(page.getByRole('heading',{name:'Ensayos de prueba',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Escuchar',exact:true}).click();
  await expect.poll(() => page.locator('audio').evaluate((a:HTMLAudioElement) => !a.paused && a.currentTime > .1),{timeout:120000}).toBe(true);
  await page.getByRole('button',{name:'Guardar cita',exact:true}).click();
  await expect(page.getByText('Cita guardada en «Citas y notas».')).toBeVisible();
  await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Pausar',exact:true}).click();
  await page.getByRole('button',{name:'Citas y notas',exact:true}).click();
  await expect(page.locator('.quote-card')).toHaveCount(1);
  const original = await page.locator('.quote-card blockquote').innerText();
  expect(original.length).toBeGreaterThan(0);
  await page.getByRole('button',{name:'Editar cita'}).click();
  await page.getByLabel('Texto de la cita',{exact:true}).fill('Una cita revisada.');
  await page.getByLabel('Comentario',{exact:true}).fill('Mi reflexión sobre la libertad.');
  await page.getByLabel('Color',{exact:true}).fill('#428566');
  await page.getByRole('button',{name:'Guardar cambios'}).click();
  await expect(page.locator('.quote-comment')).toHaveText('Mi reflexión sobre la libertad.');
  await page.reload();
  await page.getByRole('button',{name:'Citas y notas',exact:true}).click();
  await expect(page.locator('.quote-card blockquote')).toHaveText('Una cita revisada.');
  await page.getByRole('button',{name:'Copiar con referencia'}).click();
  expect((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g,'\n')).toContain('Una cita revisada.\n\nAutora de prueba — Ensayos de prueba — página');
  await page.getByText('Ver párrafo original',{exact:true}).click();
  await expect(page.locator('.quote-context')).toContainText(original);
  await page.getByLabel('Buscar citas').fill('reflexion');
  await expect(page.locator('.quote-card')).toHaveCount(1);
  await page.getByLabel('Buscar citas').fill('inexistente');
  await expect(page.locator('.quote-card')).toHaveCount(0);
  await page.getByLabel('Buscar citas').fill('');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByRole('button',{name:'Guardar cita',exact:true})).toBeInViewport();
  await page.screenshot({path:`artifacts/${test.info().project.name}-notes-mobile.png`,fullPage:true});
});
